version: 2.1
orbs:
  node: circleci/node@4.1
jobs:
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Test App
          command: |
            echo "Testing Done"
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Build App
          command: |
            echo "Building Done"