version: 2.1
orbs:
  node: circleci/node@4.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Echo hello
          command: |
            echo "Building Done"
      - run: 
          name: Front-End Install
          command: |
            npm run front-end:install
      - run: 
          name: Back-End Install
          command: |
            npm run back-end:install
      - run: 
          name: Front-End Build
          command: |
            npm run front-end:build
      - run: 
          name: Back-End Build
          command: |
            npm run back-end:build