version: 2.1
orbs:
  node: circleci/node@4.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: hello
          command: |
            echo "Hello - world"